---
- name: configurando um servidor web
  hosts: "{{maquina}}"
  vars:
   - maquina: default
  tasks:
   - name: garantdindo o apache instalado
     package:
      name: apache2
     when: ansible_os_family == "Debian"

   - name: garantindo o apache instalado em redhat
     package:
      name: httpd
     when: ansible_os_family == "RedHat"

   - name: crinando minha pagina web
     template:
      src: index
      dest: /var/www/html/index.html
